### PR TITLE
fix case sensitive match, fix service script name

### LINKED ISSUE #7: DNS lookups fail when query has capitilized domain letters
Recently, Google (`8.8.8.8`) has started sending DNS queries to resolvers [with the case intentionally changed](https://www.theregister.com/2023/01/19/google_dns_queries/) from the request. So if the query is for `1-2-3-4.domain.com` and is sent to `8.8.8.8`, it will query localtls with `1-2-3-4.doMaIn.COm` and will fail to return any results (`NXDOMAIN`).

### PR DESCRIPTION
**Pull request by mrjones-plip**
This PR:
* makes matches case insensitive for DNS query strings
* fixes service script to use bash instead of weird half python, half bash :upside_down_face: 

Closes #7

### CODE REVIEW

**Comment by mrjones-plip** [comment]
pinging @brunobg  in case PR and ticket didn't make into your inbox ; )

**Comment by brunobg** [comment]
hi @mrjones-plip thanks for the ping :) 

LGTM, but why so many commits? Did you miss a rebase on master perhaps?

**Comment by mrjones-plip** [comment]
oh - yeah - sorry about all those commits @brunobg! I'm so used to working directly on the repo, that I'm out of practice for working downstream.  Lemme clean up the PR and get back to ya!

**Comment by brunobg** [comment]
Cool, ping me when it's done and let's merge this.

**Pull request closed without merging**
